apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: marshians
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: bot 
  envs:
  - .env
resources:
- bot.yaml
